// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package config

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigAddress         = "address"
	ConfigFilePattern     = "filePattern"
	ConfigPassword        = "password"
	ConfigPrivateKeyPath  = "privateKeyPath"
	ConfigSourceDirectory = "sourceDirectory"
	ConfigUsername        = "username"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigAddress: {
			Default:     "",
			Description: "Address is the address of the sftp server to connect.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigFilePattern: {
			Default:     "*",
			Description: "Pattern to filter files in the source directory.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPassword: {
			Default:     "",
			Description: "Password is the SFTP password (can be used as passphrase if using ssh keys).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPrivateKeyPath: {
			Default:     "",
			Description: "PrivateKeyPath is the private key path for ssh login.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigSourceDirectory: {
			Default:     "",
			Description: "Directory on the remote SFTP server to retrieve files from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigUsername: {
			Default:     "",
			Description: "User is the SFTP user.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
