// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package config

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigAddress         = "address"
	ConfigBatchSize       = "batchSize"
	ConfigDirectory       = "directory"
	ConfigFilePattern     = "filePattern"
	ConfigPassword        = "password"
	ConfigPollingPeriod   = "pollingPeriod"
	ConfigPrivateKeyPath  = "privateKeyPath"
	ConfigServerPublicKey = "serverPublicKey"
	ConfigUsername        = "username"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigAddress: {
			Default:     "",
			Description: "Address is the address of the sftp server to connect.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigBatchSize: {
			Default:     "1000",
			Description: "BatchSize specifies the number of files to process in a single batch.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
				config.ValidationLessThan{V: 100001},
			},
		},
		ConfigDirectory: {
			Default:     "",
			Description: "Directory on the remote SFTP server used as the source for reading or the destination for writing files.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigFilePattern: {
			Default:     "*",
			Description: "Pattern to filter files in the source directory.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPassword: {
			Default:     "",
			Description: "Password is the SFTP password (can be used as passphrase if using ssh keys).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPollingPeriod: {
			Default:     "5s",
			Description: "This period is used by iterator to poll for new data at regular intervals.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		ConfigPrivateKeyPath: {
			Default:     "",
			Description: "PrivateKeyPath is the private key path for ssh login.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigServerPublicKey: {
			Default:     "",
			Description: "ServerPublicKey is the trusted server's public key used to validate the host during SSH connection.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigUsername: {
			Default:     "",
			Description: "User is the SFTP user.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
