// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package config

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigHost           = "host"
	ConfigPassword       = "password"
	ConfigPort           = "port"
	ConfigPrivateKeyPath = "privateKeyPath"
	ConfigUsername       = "username"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigHost: {
			Default:     "",
			Description: "Host is the host of the sftp server to connect.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigPassword: {
			Default:     "",
			Description: "Password is the SFTP password. (required with username and not required when using ssh key)",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPort: {
			Default:     "22",
			Description: "Port is the port of the sftp server to connect.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPrivateKeyPath: {
			Default:     "",
			Description: "PrivateKeyPath is the private key for ssh login.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigUsername: {
			Default:     "",
			Description: "User is the SFTP user. (required with password and not required when using ssh key)",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
