// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package config

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigHost     = "host"
	ConfigPassword = "password"
	ConfigPort     = "port"
	ConfigUser     = "user"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigHost: {
			Default:     "",
			Description: "Host is the host of the sftp server to connect.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigPassword: {
			Default:     "",
			Description: "Password is the SFTP password.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPort: {
			Default:     "22",
			Description: "Port is the port of the sftp server to connect.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigUser: {
			Default:     "",
			Description: "User is the SFTP user.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
